name: Stoneford Terraform Action
description: >
  This action runs Terraform for the Stoneford ecosystem. It can run various Terraform actions such as plan and  apply.
  It also supports running fmt and validate commands.

inputs:
  directory:
    description: The directory to run terraform in.
    required: true
  workspace:
    description: The name of the aws terraform workspace.
    required: true
  fmt:
    description: Whether to run terraform fmt.
    required: false
    default: 'false'
  validate:
    description: Whether to run terraform validate.
    required: false
    default: 'false'
  action:
    description: The terraform action to run.
    required: false
    default: ''
  account:
    description: The account name to run terraform in.
    required: true
  region:
    description: The region to run terraform in.
    required: false
    default: 'us-east-1'
  disable_backend:
    description: Whether to disable the terraform backend.
    required: false
    default: 'false'
  deployment_role:
    description: The deployment IAM role to use. If not provided, will skip configuring AWS.
    required: false
    default: ''
  tfvars-content:
    description: The content of the variable file to use.
    required: false
  
runs:
  using: composite
    
  steps:
    - name: Configure AWS credentials
      if: inputs.deployment_role != ''
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.deployment_role }}
        aws-region: ${{ inputs.region }}

    - name: Copy account specific tfvars
      env:
        SOURCE_FILE: ${{ inputs.directory }}/env/${{ inputs.account }}.tfvars
        DESTINATION_FILE: ${{ inputs.directory }}/env.auto.tfvars
      shell: bash
      run: |
        [-f "$SOURCE_FILE" ] && cp "${{env.SOURCE_FILE}}" "${{ env.DESTINATION_FILE }}"
      
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform
      id: terraform
      uses: 7Factor/action-terraform@v3
      with:
        directory: ${{ inputs.directory }}
        workspace: ${{ inputs.workspace }}
        init-args: ${{ inputs.disable_backend == 'true' && '-backend=false' || '' }}
        fmt: ${{ inputs.fmt == 'true' }}
        validate: ${{ inputs.validate == 'true' }}
        action: ${{ inputs.action }}
        backend-file: ${{ github.action_path }}/backend/s3_backend.tf
        backend-config-content: |
          bucket = "stoneford-${{ inputs.account }}-terraform-state"
          key    = "${{ inputs.region }}/terraform.tfstate"
          region = "${{ inputs.region }}"
        tfvars-content: ${{ inputs.tfvars-content }}
        comment-identifier: ${{ inputs.directory }} - ${{ inputs.account }}
        comment-header: |
          ### Terraform Results for ${{ inputs.directory }} - ${{ inputs.account }}
